<?php

use App\Core\Router;
use App\Core\Registry;
use App\Controllers\PageController;
use App\Controllers\ProductController;
use App\Controllers\UserController;
use App\Controllers\OrderController;
use App\Controllers\CaptchaController;
use App\Controllers\Admin\AdminDashboardController;
use App\Controllers\Admin\AdminUserController;
use App\Controllers\Admin\AdminOrderController;
use App\Controllers\Admin\AdminProductController;
use App\Controllers\Admin\AdminCategoryController;
use App\Middleware\AdminAuthMiddleware;
use App\Controllers\Api\OrderApiController;
use App\Controllers\Api\CartApiController;

$router = new Router();
$router->get('', [PageController::class, 'index']);
$router->get('public', [PageController::class, 'index']);
$router->get('about', [PageController::class, 'about']);
$router->get('contact', [PageController::class, 'contact']);
$router->post('contact/submit', [PageController::class, 'submitContact']);
$router->get('categories', [ProductController::class, 'showCategories']);
$router->get('products', [ProductController::class, 'listProducts']);
$router->get('register', [UserController::class, 'showRegister']);
$router->post('register', [UserController::class, 'register']);
$router->get('login', [UserController::class, 'showLogin']);
$router->post('login', [UserController::class, 'login']);
$router->get('logout', [UserController::class, 'logout']);
$router->get('order', [OrderController::class, 'showOrderForm']);
$router->post('order/process', [OrderController::class, 'processOrder']);
$router->get('orders', [OrderController::class, 'myOrders']);
$router->get('my-orders', [OrderController::class, 'myOrders']);
$router->get('order/confirmation/{id}', [OrderController::class, 'orderConfirmation']);
$router->get('order/details/{id}', [OrderController::class, 'orderDetails']);
$router->post('order/cancel/{id}', [OrderController::class, 'cancelOrder']);
$router->get('order/product/{productId}', [OrderController::class, 'showSingleProductOrderForm']);
$router->post('order/product/{productId}', [OrderController::class, 'processSingleProductOrder']);
$router->get('cart', [PageController::class, 'cart']);
$router->get('captcha', [CaptchaController::class, 'generate']);
$router->post('ajax/check-email', [UserController::class, 'checkEmail']);
$router->get('ajax/products-by-category', [ProductController::class, 'getSubcategoriesAjax']);
$router->get('ajax/subcategories', [ProductController::class, 'ajaxGetSubcategories']);
$router->post('api/cart/add', [CartApiController::class, 'add']);
$router->get('api/cart/view', [CartApiController::class, 'getCart']);
$router->post('api/cart/update', [CartApiController::class, 'update']);
$router->post('api/cart/remove', [CartApiController::class, 'remove']);
$router->post('api/cart/item/{product_id}', [CartApiController::class, 'removeItem']);
$router->post('api/cart/clear', [CartApiController::class, 'clearCart']);
$router->get('api/cart/count', [CartApiController::class, 'getCartCount']);
Router::group('api/v1', function () use ($router) {
    $router->get('orders', [OrderApiController::class, 'index']);
    $router->get('orders/{id}', [OrderApiController::class, 'show']);
    $router->put('orders/{id}', [OrderApiController::class, 'update']);
    $router->put('orders/{id}/status', [OrderApiController::class, 'updateStatus']);
});
Router::group('admin', function () use ($router) {
    $adminMiddleware = new AdminAuthMiddleware();
    $router->get('dashboard', [AdminDashboardController::class, 'index']);
    $router->get('users', [AdminUserController::class, 'index']);
    $router->get('users/{id}', [AdminUserController::class, 'show']);
    $router->get('users/{id}/edit', [AdminUserController::class, 'edit']);
    $router->post('users/{id}', [AdminUserController::class, 'update']);
    $router->post('users/{id}/reset-password', [AdminUserController::class, 'triggerPasswordReset']);
    $router->get('orders', [AdminOrderController::class, 'index']);
    $router->get('orders/{id}', [AdminOrderController::class, 'show']);
    $router->post('orders/{id}/status', [AdminOrderController::class, 'updateStatus']);
    $router->get('products', [AdminProductController::class, 'index']);
    $router->get('products/create', [AdminProductController::class, 'create']);
    $router->post('products', [AdminProductController::class, 'store']);
    $router->get('products/{id}/edit', [AdminProductController::class, 'edit']);
    $router->post('products/{id}', [AdminProductController::class, 'update']);
    $router->post('products/{id}/toggle-active', [AdminProductController::class, 'toggleActive']);
    $router->get('categories', [AdminCategoryController::class, 'index']);
    $router->get('categories/create', [AdminCategoryController::class, 'create']);
    $router->post('categories', [AdminCategoryController::class, 'store']);
    $router->get('categories/{id}/edit', [AdminCategoryController::class, 'edit']);
    $router->post('categories/{id}', [AdminCategoryController::class, 'update']);
    $router->post('categories/{id}/delete', [AdminCategoryController::class, 'destroy']);
});
return $router;